FROM python:3.9-slim
COPY . /sg_rule_log
RUN pip install -r /sg_rule_log/requirements.txt
ARG S3_BUCKET_NAME_ARG
ARG AWS_ACCESS_KEY_ID_ARG
ARG AWS_SECRET_ACCESS_KEY_ARG
ARG AWS_SESSION_TOKEN_ARG
ENV S3_BUCKET_NAME=$S3_BUCKET_NAME_ARG
ENV AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_ARG
ENV AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_ARG
ENV AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN_ARG
WORKDIR /sg_rule_log
CMD ["python", "main.py"]
