name: Daily Workflow
on:
  schedule:
  - cron: "*/10 * * * *"
  workflow_dispatch:
    inputs:
      LoggingMode:
        description: 'Enable logging mode only'
        type: boolean
        required: true
        default: 'True'
      S3bucket:
        description: 'S3 bucket name'
        type: string
        required: true
      Region:
        description: 'AWS Region'
        type: string
        required: true
        default: 'us-east-1'

jobs:
  Pull_and_run_latest:
    runs-on: ubuntu-latest
    steps:  
      - name: Docker Hub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: docker image pull
        run: docker pull ${{ vars.DOCKER_REPOSITORY_TAG }}
      - name: docker container run
        run:  docker run -e REGION -e LOGGING_MODE -e S3_BUCKET_NAME -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY  -e AWS_SESSION_TOKEN --rm maordockr89/sg_rule_logger:latest
        env:
          REGION: ${{github.event.inputs.Region || 'us-east-1'}}
          LOGGING_MODE: ${{github.event.inputs.LoggingMode || 'true'}}
          S3_BUCKET_NAME: ${{ vars.S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
  