name: Daily Workflow
on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:
    inputs:
      LoggingMode:
        description: 'Enable logging mode only'
        type: boolean
        required: true
        default: 'True'

jobs:
  Build_latest:
    runs-on: ubuntu-latest
    steps:  
      - name: Checkout 
        uses: actions/checkout@v2 # Required to mount the Github Workspace to a volume 
      - uses: addnab/docker-run-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.io/${{ secrets.DOCKER_USERNAME }}/sg_rule_logger
          image: maordockr89/sg_rule_logger:latest
          options: -e LOGGING_MODE=True
          run: |
            echo "Running Script"
            /work/sg_rule_log/main
  