name: Daily Workflow
on:
  schedule:
    - cron: "0 8 * * *"
  workflow_call:
    inputs:
      LoggingMode:
        description: 'Enable logging mode only'
        type: boolean
        required: true
        default: 'True'
      S3bucket:
        description: 'S3 bucket name'
        type: string
        required: true
        default: 'sg-rules-moon'


  workflow_dispatch:
    inputs:
      LoggingMode:
        description: 'Enable logging mode only'
        type: boolean
        required: true
        default: 'True'
      S3bucket:
        description: 'S3 bucket name'
        type: string
        required: true
        default: 'sg-rules-moon'

jobs:
  Pull_and_run_latest:
    runs-on: ubuntu-latest
    steps:  
      - name: Docker Hub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: docker image pull
        run: docker pull maordockr89/sg_rule_logger:latest
      - name: docker container run
        run:  docker run -e LOGGING_MODE=${{github.event.inputs.LoggingMode}} -e S3_BUCKET_NAME=${{github.event.inputs.S3bucket}} -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}  -e AWS_SESSION_TOKEN=${{ secrets.AWS_SESSION_TOKEN }} --rm maordockr89/sg_rule_logger:latest
       
  