name: Daily Workflow
on:
  schedule:
    - cron: "0 8 * * *"
  workflow_call:
    inputs:
      LoggingMode:
        description: 'Enable logging mode only'
        type: boolean
        required: true
        default: 'True'

  workflow_dispatch:
    inputs:
      LoggingMode:
        description: 'Enable logging mode only'
        type: boolean
        required: true
        default: 'True'

jobs:
  Build and run latest:
    runs-on: ubuntu-latest
    steps:  
      - name: Docker Hub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: docker image pull
        run: docker pull maordockr89/sg_rule_logger:latest
      - name: docker container run
        run:  docker run -it -e LOGGING_MODE=${{github.event.inputs.LoggingMode}} --rm maordockr89/sg_rule_logger:latest
       
  