name: Docker Build and Push
on:
  push:

jobs:
  Build_latest:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v3
      - name: Docker Hub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: maordockr89/sg_rule_logger:latest
          build-args: |
            S3_BUCKET_NAME=${{secrets.S3_BUCKET_NAME}}
            AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY_ID}}
            AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}}
            AWS_SESSION_TOKEN=${{secrets.AWS_SESSION_TOKEN}}
